# Generated by Django 3.0.7 on 2020-08-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0002_h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='author',
        ),
        migrations.DeleteModel(
            name='h',
        ),
        migrations.DeleteModel(
            name='hospital',
        ),
    ]
