# Generated by Django 3.0.7 on 2020-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0005_hospital_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('hospital_id', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=100)),
                ('why', models.CharField(max_length=5000)),
            ],
        ),
    ]
