# Generated by Django 3.0.7 on 2020-08-17 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hand', '0006_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=500)),
                ('location', models.URLField(max_length=5000)),
                ('no_of_rooms', models.IntegerField()),
                ('is_a', models.CharField(choices=[('Hotel', 'Hotel'), ('School', 'School')], default='Hospital', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
