# Generated by Django 3.0.7 on 2020-08-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0007_basic_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='currently_a',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('School', 'School')], default='Hospital', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='no_of_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='basic_info',
        ),
    ]
