# Generated by Django 3.0.7 on 2020-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0011_auto_20200817_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='corona_test_availability',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
    ]
