# Generated by Django 3.0.7 on 2020-08-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0013_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='citizionship_no',
            new_name='citizenship_no',
        ),
    ]
