# Generated by Django 3.0.7 on 2020-09-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0014_auto_20200823_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='region',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Janakpur', 'Janakpur'), ('Pokhara', 'Pokhara'), ('Dhulikhel', 'Dhulikhel')], default='Janakpur', max_length=100),
        ),
    ]
