# Generated by Django 3.0.7 on 2020-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0015_hospital_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Janakpur', 'Janakpur'), ('Pokhara', 'Pokhara'), ('Dhulikhel', 'Dhulikhel')], max_length=100),
        ),
    ]
