# Generated by Django 3.0.7 on 2020-09-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0016_auto_20200906_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('feedback', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
            },
        ),
    ]
