# Generated by Django 3.0.7 on 2020-09-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0017_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='message',
        ),
    ]
