# Generated by Django 3.0.7 on 2020-09-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0018_auto_20200912_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='info',
            new_name='website',
        ),
    ]
