# Generated by Django 3.0.7 on 2020-09-21 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0019_auto_20200920_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='delete_request',
            name='hospital_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hand.hospital'),
            preserve_default=False,
        ),
    ]
