# Generated by Django 3.0.7 on 2020-09-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0020_delete_request_hospital_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delete_request',
            name='hospital_info',
        ),
    ]
