# Generated by Django 3.0.7 on 2020-09-21 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hand', '0021_remove_delete_request_hospital_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='delete_request',
            name='hospital_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hand.hospital'),
            preserve_default=False,
        ),
    ]
